//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml.Serialization;


namespace VsGallery.Core.Vsix.Schemas {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    [XmlRoot(Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010", IsNullable=false)]
    public partial class Vsix {
        
        private VsixIdentifier identifierField;
        
        private VsixReference[] referencesField;
        
        private VsixContent contentField;
        
        private string versionField;
        
        /// <remarks/>
        public VsixIdentifier Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("Reference", IsNullable=false)]
        public VsixReference[] References {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        public VsixContent Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    public partial class VsixIdentifier {
        
        private string nameField;
        
        private string authorField;
        
        private string versionField;
        
        private string descriptionField;
        
        private ushort localeField;
        
        private string moreInfoUrlField;
        
        private string licenseField;
        
        private string gettingStartedGuideField;
        
        private string releaseNotesField;
        
        private string iconField;
        
        private string previewImageField;
        
        private bool installedByMsiField;
        
        private bool installedByMsiFieldSpecified;
        
        private object[] supportedProductsField;
        
        private VsixIdentifierSupportedFrameworkRuntimeEdition supportedFrameworkRuntimeEditionField;
        
        private bool systemComponentField;
        
        private bool systemComponentFieldSpecified;
        
        private bool allUsersField;
        
        private bool allUsersFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ushort Locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        public string MoreInfoUrl {
            get {
                return this.moreInfoUrlField;
            }
            set {
                this.moreInfoUrlField = value;
            }
        }
        
        /// <remarks/>
        public string License {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
            }
        }
        
        /// <remarks/>
        public string GettingStartedGuide {
            get {
                return this.gettingStartedGuideField;
            }
            set {
                this.gettingStartedGuideField = value;
            }
        }
        
        /// <remarks/>
        public string ReleaseNotes {
            get {
                return this.releaseNotesField;
            }
            set {
                this.releaseNotesField = value;
            }
        }
        
        /// <remarks/>
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string PreviewImage {
            get {
                return this.previewImageField;
            }
            set {
                this.previewImageField = value;
            }
        }
        
        /// <remarks/>
        public bool InstalledByMsi {
            get {
                return this.installedByMsiField;
            }
            set {
                this.installedByMsiField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool InstalledByMsiSpecified {
            get {
                return this.installedByMsiFieldSpecified;
            }
            set {
                this.installedByMsiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("IsolatedShell", typeof(VsixIdentifierIsolatedShell), IsNullable=false)]
        [XmlArrayItem("VisualStudio", typeof(VsixIdentifierVisualStudio), IsNullable=false)]
        public object[] SupportedProducts {
            get {
                return this.supportedProductsField;
            }
            set {
                this.supportedProductsField = value;
            }
        }
        
        /// <remarks/>
        public VsixIdentifierSupportedFrameworkRuntimeEdition SupportedFrameworkRuntimeEdition {
            get {
                return this.supportedFrameworkRuntimeEditionField;
            }
            set {
                this.supportedFrameworkRuntimeEditionField = value;
            }
        }
        
        /// <remarks/>
        public bool SystemComponent {
            get {
                return this.systemComponentField;
            }
            set {
                this.systemComponentField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool SystemComponentSpecified {
            get {
                return this.systemComponentFieldSpecified;
            }
            set {
                this.systemComponentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AllUsers {
            get {
                return this.allUsersField;
            }
            set {
                this.allUsersField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool AllUsersSpecified {
            get {
                return this.allUsersFieldSpecified;
            }
            set {
                this.allUsersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    public partial class VsixIdentifierIsolatedShell {
        
        private string versionField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    public partial class VsixIdentifierVisualStudio {
        
        private string[] editionField;
        
        private string versionField;
        
        /// <remarks/>
        [XmlElement("Edition")]
        public string[] Edition {
            get {
                return this.editionField;
            }
            set {
                this.editionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    public partial class VsixIdentifierSupportedFrameworkRuntimeEdition {
        
        private string minVersionField;
        
        private string maxVersionField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string MinVersion {
            get {
                return this.minVersionField;
            }
            set {
                this.minVersionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string MaxVersion {
            get {
                return this.maxVersionField;
            }
            set {
                this.maxVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    public partial class VsixReference {
        
        private string nameField;
        
        private string moreInfoUrlField;
        
        private string vsixPathField;
        
        private string idField;
        
        private string minVersionField;
        
        private string maxVersionField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string MoreInfoUrl {
            get {
                return this.moreInfoUrlField;
            }
            set {
                this.moreInfoUrlField = value;
            }
        }
        
        /// <remarks/>
        public string VsixPath {
            get {
                return this.vsixPathField;
            }
            set {
                this.vsixPathField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string MinVersion {
            get {
                return this.minVersionField;
            }
            set {
                this.minVersionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string MaxVersion {
            get {
                return this.maxVersionField;
            }
            set {
                this.maxVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    public partial class VsixContent {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [XmlElement("Assembly", typeof(VsixAssembly))]
        [XmlElement("CustomExtension", typeof(VsixCustomExtension))]
        [XmlElement("ItemTemplate", typeof(object))]
        [XmlElement("MefComponent", typeof(object))]
        [XmlElement("ProjectTemplate", typeof(object))]
        [XmlElement("Sample", typeof(VsixSample))]
        [XmlElement("ToolboxControl", typeof(object))]
        [XmlElement("VsPackage", typeof(object))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    public partial class VsixAssembly {
        
        private string assemblyNameField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string AssemblyName {
            get {
                return this.assemblyNameField;
            }
            set {
                this.assemblyNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    public partial class VsixCustomExtension {
        
        private string typeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAnyAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010")]
    public partial class VsixSample {
        
        private string programmingLanguagesField;
        
        private string targetFrameworksField;
        
        private string categorizationPathField;
        
        private string startupFilesField;
        
        private string defaultNameField;
        
        private string solutionPathField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string ProgrammingLanguages {
            get {
                return this.programmingLanguagesField;
            }
            set {
                this.programmingLanguagesField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string TargetFrameworks {
            get {
                return this.targetFrameworksField;
            }
            set {
                this.targetFrameworksField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string CategorizationPath {
            get {
                return this.categorizationPathField;
            }
            set {
                this.categorizationPathField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string StartupFiles {
            get {
                return this.startupFilesField;
            }
            set {
                this.startupFilesField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string DefaultName {
            get {
                return this.defaultNameField;
            }
            set {
                this.defaultNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string SolutionPath {
            get {
                return this.solutionPathField;
            }
            set {
                this.solutionPathField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://schemas.microsoft.com/developer/vsx-schema/2010", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Assembly,
        
        /// <remarks/>
        CustomExtension,
        
        /// <remarks/>
        ItemTemplate,
        
        /// <remarks/>
        MefComponent,
        
        /// <remarks/>
        ProjectTemplate,
        
        /// <remarks/>
        Sample,
        
        /// <remarks/>
        ToolboxControl,
        
        /// <remarks/>
        VsPackage,
    }
}
